"keyword" = "pink"
"operator" = "pink"

"function" = "blue"
"type" = "blue"
"variable.other.member" = "blue"

"string" = "cyan"

"namespace" = "yellow"

"constant.builtin" = "purple"

"constant.numeric" = "orange"

"variable" = "fg"
"punctuation" = "fg"

"comment" = { fg = "grey", modifiers = ["italic"] }

"ui.background" = { bg = "bg_dark" }
"ui.selection" = { bg = "bg_selection" } 
"ui.statusline" = { fg = "fg", bg = "bg_status" }
"ui.statusline.normal" = { fg = "bg_dark", bg = "green", modifiers = ["bold"] }
"ui.popup" = { fg = "fg", bg = "bg_status" }


[palette]
fg = "#c0caf5"
pink = "#f7768e"
blue = "#7aa2f7"
cyan = "#73daca"
yellow = "#e0af68"
purple = "#bb9af7"
orange = "#a7955e"
green = "#9ece6a"
grey = "#5c6370"

bg_dark = "#01001a"
bg_status = "#1f2335"
bg_selection = "#212030" 
