format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](yellow)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"

[git_branch]
format = "[$branch]($style)"
style = "bright-blue"
symbol = '🌱 '

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
# ~/.config/starship.toml

[rust]
format = 'via [⚙️ $version](red bold)'

[scala]
symbol = '🌟 '

[odin]
format = 'via [󰹩 ($version )]($style)'
show_commit = true
symbol = 'Ø '

[ocaml]
format = 'via [🐪 $version]($style) '

[lua]
format = 'via [🌕 $version](bold blue) '
symbol = '🌙 '

[julia]
symbol = '∴ '

[c]
format = 'via [$name $version]($style)'

[golang]
format = 'via🏎[🏎💨($version )($mod_version )]($style)'

[elixir]
symbol = '💧 '

[zig]
symbol = '⚡️ '

[mise]
health = 'ready'

[nix_shell]
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '

[container]
format = '[$symbol \[$name\]]($style) '
