[[language]]
name = "go"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "zig"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "hyprlang"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "odin"
auto-format = false
file-types = ["odin"]
language-servers = [ "ols" ]
comment-token = "//"
indent = { tab-width = 2, unit = " " }
injection-regex = "odin"
formatter = { command = "odinfmt", args = [ "-stdin", "true" ] }

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"

[[language]]
name = "rust"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
