# general
[manager]
marker_copied   = { fg = "#a6da95", bg = "#a6da95" } # green
marker_cut      = { fg = "#ed8796", bg = "#ed8796" } # red
marker_marked   = { fg = "#c6a0f6", bg = "#c6a0f6" } # magenta
marker_selected = { fg = "#b7bdf8", bg = "#b7bdf8" } # cyan

cwd = { fg = "#eed49f" } # yellow
hovered = { reversed = true }
preview_hovered = { reversed = true }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# default bg
count_copied   = { fg = "#a6da95", bg = "#a6da95" } # green
count_cut      = { fg = "#ed8796", bg = "#ed8796" } # red
count_selected = { fg = "#eed49f", bg = "#eed49f" } # yellow

border_symbol = "│"
border_style = { fg = "#cad3f5"} # white

# status-line
[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "reset", bg = "#363a4f" } # light bg

# default bg
mode_normal = { fg = "#8aadf4", bg = "#8aadf4", bold = true } # blue
mode_select = { fg = "#c6a0f6", bg = "#c6a0f6", bold = true } # magenta
mode_unset  = { fg = "#eed49f", bg = "#eed49f", bold = true } # yellow

# blue - light bg
progress_label  = { fg = "#8aadf4", bg = "#8aadf4", bold = true }
# light bg - default bg
progress_normal = { fg = "#a6da95", bg = "#a6da95" }
progress_error  = { fg = "#ed8796", bg = "#ed8796" }

permissions_t = { fg = "#a6da95" } # green
permissions_r = { fg = "#eed49f" } # yellow
permissions_w = { fg = "#ed8796" } # red
permissions_x = { fg = "#8aadf4" } # cyan
permissions_s = { fg = "#c6a0f6" } # magenta

[select]
border   = { fg = "#8aadf4" } # blue
active   = { fg = "#c6a0f6", bold = true } # magenta
inactive = {}

[input]
border   = { fg = "#8aadf4" } # blue
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#8aadf4" } # blue
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#8aadf4" } # blue
title   = {}
hovered = { fg = "#c6a0f6" } # magenta

[which]
cols = 2
separator = " - "
separator_style = { fg = "#494d64" } # darkgrey
mask = { bg = "#24273a" } # dark bg
rest = { fg = "#494d64" } # darkgrey
cand = { fg = "#cad3f5" }
desc = { fg = "#cad3f5" }

[help]
on      = { fg = "#8aadf4" } # cyan
run     = { fg = "#b7bdf8" } # magenta
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#494d64", bg = "#494d64" } # white

[notify]
title_info  = { fg = "#a6da95" } # green
title_warn  = { fg = "#eed49f" } # yellow
title_error = { fg = "#ed8796" } # red

# files
[filetype]
rules = [
    { mime = "image/*", fg = "#ee99a0" },
    { mime = "{audio,video}/*", fg = "#c6a0f6" },
    { mime = "application/{,g}zip", fg = "#f5a97f" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f5a97f" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#5b6078" },
    { name = "*", is = "orphan", fg = "#c6a0f6" },
    { name = "*", is = "exec", fg = "#c6a0f6" },
    { name = "*/", fg = "#c6a0f6"}
]
