# general
[manager]
marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" } # green
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" } # red
marker_marked   = { fg = "#cba6f7", bg = "#cba6f7" } # magenta
marker_selected = { fg = "#b4befe", bg = "#b4befe" } # cyan

cwd = { fg = "#f9e2af" } # yellow
hovered = { reversed = true }
preview_hovered = { reversed = true }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# default bg
count_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" } # green
count_cut      = { fg = "#f38ba8", bg = "#f38ba8" } # red
count_selected = { fg = "#f9e2af", bg = "#f9e2af" } # yellow

border_symbol = "│"
border_style = { fg = "#cdd6f4"} # white

# status-line
[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "reset", bg = "#26263a" } # light bg

# default bg
mode_normal = { fg = "#89b4fa", bg = "#89b4fa", bold = true } # blue
mode_select = { fg = "#cba6f7", bg = "#cba6f7", bold = true } # magenta
mode_unset  = { fg = "#f9e2af", bg = "#f9e2af", bold = true } # yellow

# blue - light bg
progress_label  = { fg = "#89b4fa", bg = "#89b4fa", bold = true }
# light bg - default bg
progress_normal = { fg = "#a6e3a1", bg = "#a6e3a1" }
progress_error  = { fg = "#f38ba8", bg = "#f38ba8" }

permissions_t = { fg = "#a6e3a1" } # green
permissions_r = { fg = "#f9e2af" } # yellow
permissions_w = { fg = "#f38ba8" } # red
permissions_x = { fg = "#89b4fa" } # cyan
permissions_s = { fg = "#cba6f7" } # magenta

[select]
border   = { fg = "#89b4fa" } # blue
active   = { fg = "#cba6f7", bold = true } # magenta
inactive = {}

[input]
border   = { fg = "#89b4fa" } # blue
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#89b4fa" } # blue
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#89b4fa" } # blue
title   = {}
hovered = { fg = "#cba6f7" } # magenta

[which]
cols = 2
separator = " - "
separator_style = { fg = "#353552" } # darkgrey
mask = { bg = "#161622" } # dark bg
rest = { fg = "#353552" } # darkgrey
cand = { fg = "#cdd6f4" }
desc = { fg = "#cdd6f4" }

[help]
on      = { fg = "#89b4fa" } # cyan
run     = { fg = "#b4befe" } # magenta
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#353552", bg = "#353552" } # white

[notify]
title_info  = { fg = "#a6e3a1" } # green
title_warn  = { fg = "#f9e2af" } # yellow
title_error = { fg = "#f38ba8" } # red

# files
[filetype]
rules = [
    { mime = "image/*", fg = "#eba0ac" },
    { mime = "{audio,video}/*", fg = "#cba6f7" },
    { mime = "application/{,g}zip", fg = "#fab387" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#fab387" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#3d3d5d" },
    { name = "*", is = "orphan", fg = "#cba6f7" },
    { name = "*", is = "exec", fg = "#cba6f7" },
    { name = "*/", fg = "#cba6f7"}
]
