# Ferra
#License
	# Ferra is released under the MIT License.
# Thanks to https://github.com/casperstorm/ferra

background #2b292d
foreground #fecdb2

selection_background #4d424b
selection_foreground #fecdb2

cursor #fecdb2
cursor_text_color background

# Black
color0  #1f1e20
color8  #2b292d

# Red
color1  #c05862
color9  #e06b75

# Green
color2  #b1b695
color10 #9f9f7c

# Yellow
color3  #f5d76e
color11 #fff27a

# Blue
color4  #ffa07a
color12 #e88c6f

# Magenta
color5  #f6b6c9
color13 #ffb9cc

# Cyan
color6  #bfbfcf
color14 #d1d1e0

# White
color7  #f5f5f5
color15 #ffffff
